### PR TITLE
Add MeanWell IRM-02 ACDC converter (THT)

### PR DESCRIPTION
**Pull request by Roman3349**
Datasheet: http://www.meanwell.com/productPdf.aspx?i=675
picture

Signed-off-by: Roman3349 <ondracek.roman@centrum.cz>

### CODE REVIEW

**Comment by Roman3349** [comment]
@jkriege2 Please, look at this.

**Comment by jkriege2** [comment]
Hi!

there is an updated KLC rule that requires 0.12mm width of the SilkS. Please change ... otherwise it looks fine!

Best,
JAN

**Comment by Roman3349** [comment]
@jkriege2 @ashtonchase Fixed. :)

**Comment by jkriege2** [comment]
nice work!
Thanks,
JAN

**Pull request merged**
