### PR TITLE
Add 3D model of MeanWell IRM-02-x

### PR DESCRIPTION
**Pull request by Roman3349**
Signed-off-by: Roman Ondráček <ondracek.roman@centrum.cz>

### CODE REVIEW

**Comment by Roman3349** [comment]
KiCad/kicad-library#1252

**Comment by poeschlr** [comment]
The stable kicad version does not support step for 3d models. For this reason the file ending in the footprint should be .wrl

@SchrodingersGat the klc is not clear about this. Am i wrong with my assumption or should we add this information to the klc.

**Comment by SchrodingersGat** [comment]
I have amended the KLC to only allow .wrl

**Comment by Shackmeister** [comment]
Hi @Roman3349 can you please update the 3D file ending so this can be merged? :)

**Comment by Roman3349** [comment]
I am sorry that I did not progress with this pull request. Because I had not got enough free time to finish work on this pull request. I want finish work on this pull request as soon as possible.

**Comment by SchrodingersGat** [comment]
@Roman3349 I am marking this repository as archived - please resubmit this PR to https://github.com/kicad/kicad-footprints :)

**Pull request closed without merging**
