### PR TITLE
Add TMR 1(2) TRACO Power DC/DC converters in SIP6(8) package

### PR DESCRIPTION
**Pull request by eldarkg**
[Datasheet](http://assets.tracopower.com/20160407154341/TMR1/documents/tmr1-datasheet.pdf)
- Single output
  Single output
- Dual output
  Dual output

### CODE REVIEW

**Comment by eldarkg** [comment]
TMR (Single/Dual, 2 Watts)
[Datasheet](http://assets.tracopower.com/20160415081036/TMR2/documents/tmr-datasheet.pdf)
tmr

**Comment by ashtonchase** [comment]
Hi @eldarkg, 

**DCDC-Conv_TRACO_TMR_1-xxxx_Single**
**DCDC-Conv_TRACO_TMR_1-xxxx_Dual**
- Per KLC 10.3, please update the keywords field. It is givig the violation because of the commas.
- The silkscreen outline is the exact size as the component, which means you won't see the silkscreen upon installation. Per KLC 6.5, please increase the outline dimensions to ~17.8 x 8.12mm. 

**DCDC-Conv_TRACO_TMR_xxxx**
- Per KLC 10.3, please update the keywords field. It is giving the violation because of the commas.
- Suggestion: Add silkscreen to the pins that are common single/dual: pins 1,2,3,5,6. If you can creatively depict the differences, that would be great too, but not required. 

Thanks!

**Comment by eldarkg** [comment]
Fixed.
dual
dual1
single1

**Comment by eldarkg** [comment]
But silkscreen text will be not visible after install packages. I did that how it made other components in the library

**Comment by ashtonchase** [comment]
Hi @eldarkg,

All issues have been resolved. Looks good! I'm merging now. Thank you for your contribution!

**Comment by eldarkg** [comment]
Ok :)

**Pull request merged**
