### PR TITLE
Added TRACO ten20win footprint

### PR DESCRIPTION
**Pull request by dejfson**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

same as for you smybol on this ... please have a look at the (new version of) the KLCs. Some things you need to change befopre we can merge:
1. rotate 90° CCW so pin1 is top left
2. add the exact outline of the package on F.Fab (width 0.1mm)
3. add a second label of F.Fab with text `%R` This will add a REFDES on the F.FAB layer (cou can psoition it over the REFDES on F.SilkS)
4. F.SilkS should have a line-width of 0.12mm and please ensure that it is visible after assembling package (i.e. it should be offset bei ~0.05-0.12mm from the F.Fab-outline)
5. make pin1 rectangular (non-rounded)
6. remove the +Vout, ... texts and the footprint name in the center that's already there on F.Fab ....

best,
JAN

**Comment by jkriege2** [comment]
PS: As I mentioned that with the symbol: Name is OK!

**Comment by jkriege2** [comment]
Hi!

OK, mostly good ... I spotted three things:
1. You can move the silkscreen a bit close ;-) ... usually we offset it ~0.1mm from the outline. then it's JUST visible
2. the courtyard should be closer to the outline. Here the offset should be 0.25mm
3. Do you really need the text next to the pins? If it's not there, the footprint is more general! If you really need it, I would suggest placing it separately on the PCB

Best,
JAN

**Comment by dejfson** [comment]
ok, give me a bit of time, i'll change it and push

**Comment by dejfson** [comment]
ok, have a look pls.

**Comment by jkriege2** [comment]
Great Work!

Thanks,
JAN

**Comment by dejfson** [comment]
ok, thanks

**Pull request merged**
