### PR TITLE
Created Infineon IR3898

### PR DESCRIPTION
**Pull request by ashtonchase**
[Device datasheet](http://www.infineon.com/dgdl/ir3898m.pdf?fileId=5546d462533600a4015355d5ebb01815)

I acknowledge the KLC 10.6 violation, as non inherited attributes have been applied.
**Note:** PCB Copper and Soldermasks are not 1:1 in datasheet. 
image

This was mimiced in the footprint.
image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hey Ashton, super detailed work! Is there a particular reason that you have not followed the stencil guideline in the datasheet?

paste

**Comment by ashtonchase** [comment]
I was some time ago that I created this footprint. Let me go back and see if I can re-create exactly what they have. I'll let you know in a few hours.

**Comment by ashtonchase** [comment]
The paste mask has been updated. 
image

**Comment by SchrodingersGat** [comment]
Sweet, nice work.

**Pull request merged**
