### PR TITLE
Footprint for muRata NMA dc/dc converters

### PR DESCRIPTION
**Pull request by cedricboudinet**
Related to [https://github.com/KiCad/kicad-library/pull/1160](url)
The doc can be found here: http://power.murata.com/data/power/ncl/kdc_nma.pdf
Here are some screenshots:
nma_dc
nma_sc

### CODE REVIEW

**Comment by poeschlr** [comment]
Please add pin 1 markers on fab and silk layers. ([klc](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) points 7.3.vi .. 7.3.viii and 7.4.ii.c)
There should also be a link to the datasheet in the description field. (KLC 10.2.i)
Maybe also add the DCDC-Converter keyword to the keyword field.

**Comment by cedricboudinet** [comment]
@poeschlr : I updated the footprints, tell me if it's ok.
I am not use that I have a clear view of the purpose of each layer. Is it explained in the documentation?

**Comment by poeschlr** [comment]
The pin 1 marker on the silkscreen needs to be visible after assembly.
The pin 1 marker on the fab layer is still missing.
For the later maybe use a chamfer of the corner nearest to pin 1.
The former with a marking of the corner nearest to pin 1 or you can use an arrow.

An example from my personal library. (Not yet committed to this lib because my personal standards are a bit different to klc and i am currently a bit short on time.)
screenshot from 2017-04-11 10-38-31

**Comment by cedricboudinet** [comment]
@poeschlr : I updated the footprint and the symbol in kicad-library.

**Comment by poeschlr** [comment]
Looks good to me.

I think if you would put the reference of the DCDC-Conv_muRata_NMAxxxxSC all should be done.
[KLC](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention) 7.4.iii.a
Could look something like this. 
screenshot from 2017-04-15 12-08-22

Maybe also make the chamfer a bit bigger. (It's hard to see right now.)
From the [FAQ](https://github.com/KiCad/kicad-library/wiki/Frequently-asked-questions)
> The size of this bevel should be 1mm or 25% of the package size, whichever is smaller.

**Comment by jkriege2** [comment]
nice work!

Thanks,
JAN

**Pull request merged**
