### PR TITLE
changed to satisfy some KLC rules

### PR DESCRIPTION
**Pull request by michal777**
Pad 1 at (0,0).
Added Courtyard.
Some renaming: Converter and CONV to Conv (for consistency)
Some texts on silkscreen moved inside (for consistency, I'm not sure if it should be inside or outside).

### CODE REVIEW

**Comment by CarlPoirier** [comment]
Hi Michal,

Did you add the courtyard using a script?

**Comment by michal777** [comment]
Yes, the rectangle courtyards were added with script (ansi C).

Edit:
https://github.com/michal777/Footprint_Utils/blob/master/CrtYd_Gen/

There is also script to remove courtyard, rotate all .pretty, move all so that pin 1 is at 0 and tool that places ref and val above footprint. They are simple and can destroy footprint (If somebody will use - use with caution).

**Comment by CarlPoirier** [comment]
OK. I a day or so, I will commit the amendment of the courtyard rule 6.6 if
I haven't got any other comment about it. You would then need to run the
script again with a clearance of 0.25mm.

**Comment by michal777** [comment]
Courtyard changed, it's 0.25 mm from body, assuming that body dimensions are the same as dimensions of silkscreen (I have not verified it).

**Comment by CarlPoirier** [comment]
Great Michal, thanks a bunch!

**Pull request merged**
