### PR TITLE
Add Hahn HS-400XX footprint

### PR DESCRIPTION
**Pull request by svheymann**
Datasheet is not directly available from Hahn

### CODE REVIEW

**Comment by jkriege2** [comment]
Nice work!

The only other thing: Please make silkscreen lines 0.12mm thick ... and add the datasheet link to the DOC-field

Then I'll merge!
JAN

**Comment by svheymann** [comment]
I fixed the line width, but i dont have any other links other than the one that is already there. Hahn seems not to provide any download area for datasheets so i had to use a distributor download link.

**Comment by svheymann** [comment]
One other thing: Hahn numbers the pins 1,5,7 and 9, which is also printed on the housing and i also used this on the footprint. Should i build a matching symbol for this or renumber the footprint pins? Otherwise the pin mapping wont work i guess?

**Comment by jkriege2** [comment]
Hi!

oh, sorry that remark on datasheet was a leftover of a comment-draft (didn't see the link you already had)! Just ignore that ;-)

ad 2) Yes, please make a matching Symbol (best with aliases for each volatge) that links to this footprint (footprint field+FPFilters)!.

Best,
JAN

**Pull request merged**
