### PR TITLE
new footprint for TRACO TMR-1SM

### PR DESCRIPTION
**Pull request by hvraven**
This adds a footprint for the SMD versions of the TRACO TMR-1. Some comments on the footprint would be great, this is my first completely self-made footprint.

Library pull request: https://github.com/KiCad/kicad-library/pull/1534

tmr-1sm_footprint

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

please set the SMD-attribute as Travis suggests:
klc_10_smd

Best,
JAN

**Comment by jkriege2** [comment]
I had a look at the actual footpritn now ... except the SMD attribute (see my last post), you only need to the the 3D model link to `${KISYS3DMOD}/Converters_DCDC_ACDC.3dshapes/DCDC-Conv_TRACO_TMR-1SM.wrl` (the if someone creates the model it will be displayed without changes to the footprint!)

Best,
JAN

**Comment by hvraven** [comment]
Thanks for looking into it, I made the changes. Thanks for the picture above, I first did not find the SMD attribute as it is called Normal+Insert in my installation. I hope it is now as desired.

**Comment by jkriege2** [comment]
nice work!
Thanks,
JAN

**Pull request merged**
