### PR TITLE
Add footprint for Traco Power TSR-1 DC/DC regulators.

### PR DESCRIPTION
**Pull request by Schlumpf**
PR for symbol and 3D model: https://github.com/KiCad/kicad-library/pull/577

### CODE REVIEW

**Comment by ashtonchase** [comment]
Hi @Schlumpf ,
A few items: 
Please remove the silkscreen from the technical layers in the pad properties dialog.I removed it from pin 1 here,  
image

Also, please indicate pin 1. Much like the snapshot below: 
image

Also, the silkscreen needs to be expanded around all sides, as based upon the datasheet and your 3d model, the silkscreen will not be visible upon assembly. Refer to [KLC rule 6.5](https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention). Adding the 2x width of the silkscreen would give you an outer dimension of 12w x 7.9h.

**Comment by SchrodingersGat** [comment]
Also I would suggest making pad-1 rectangular, as this helps identify it more easily, even if you don't have any silkscreen, or you're looking from the other side of the PCB.

**Comment by Schlumpf** [comment]
Thanks, I corrected this PR. I added a dot as pad 1 marker, because there is a dot on the device, too. Or is a number strictly required?

**Comment by ashtonchase** [comment]
Thanks for your contribution, @Schlumpf !

**Pull request merged**
