### PR TITLE
New footprints

### PR DESCRIPTION
**Pull request by mistoll**
MeanWell NID60 and Recom R-78HBxx-0.5 footprints.

Comments appreciated.

### CODE REVIEW

**Comment by michal777** [comment]
Rule 6.2 broken.

**Comment by mistoll** [comment]
The origin is now in pin 1.
Any thoughts about naming?

**Comment by michal777** [comment]
Names are ok. I think it would be better to change Value to VAL*\* and Reference to name of footprint (but I still don't know if some rules about them will be added to convention).

**Comment by mistoll** [comment]
VAL*\* and Reference changed.

**Comment by michal777** [comment]
Thanks. I will do courtard for footprint this library.

**Pull request merged**
