### PR TITLE
Added NXE2

### PR DESCRIPTION
**Pull request by Matyro**
Added foodprint for muRata 2W isolated power supply
http://power.murata.com/data/power/ncl/kdc_nxe2.pdf

You can find the symbol under:
https://github.com/KiCad/kicad-library/pull/1442

footprint

### CODE REVIEW

**Comment by ghost** [comment]
Posting updated image for reference.

image

**Comment by ghost** [comment]
Hi @matyro  Thanks for making those changes.  Some further review points ...

1. The datasheet shows the pick and place origin for this component. This supersedes the usual rule of "origin at centre" - see KLC 8.2.i.  Please move the footprint leftwards to align the pick and place origin with the (0,0) grid point.

image

2. Please break the silkscreen lines so that they do not cross the pads.  There should be 0.2mm clearance between lines and pads

3. The courtyard outline needs to be outside the area of the body **and** the pads.  The top and bottom lines therefore need to move so that they are 0.25mm away from the end of the pads.

image

4. The datasheet shows an "isolation barrier" in the footprint.  Is this a keep-out zone in which no other components or tracks are allowed?  There was a recent PR that involved keep-out zones; I will look for details.

**EDIT**  Example of keep-out zone on Fab layer here: https://github.com/KiCad/Connectors_Hirose.pretty/pull/17

image

**Comment by Shackmeister** [comment]
@hackscribble according to KLC the clearance should be 0.2mm between pads and silkscreen

**Comment by ghost** [comment]
> according to KLC the clearance should be 0.2mm between pads and silkscreen

That was my point (2) above :smile: or am I missing a different point?

**Comment by Shackmeister** [comment]
@hackscribble sorry my bad I probably mixed it with 0.25mm from the courtyard xD

**Comment by poeschlr** [comment]
I think the keepout is better on user dwgs layer.
Example: https://github.com/KiCad/RF_Modules.pretty/pull/16
The fab layer is used for the documentation or for manufacturing. Keepout zones are only important while routing the board. (I would not like to have them in the documentation afterwards.)

We should fix this in KLC 
I opened an [issue](https://github.com/KiCad/kicad-library/issues/1443) for that discussion.

**Comment by Matyro** [comment]
Keepout is now on Dwgs.User

Travis Check for part center is now failing because i moved the part 1.27mm (0.5'') to set 0,0 to pick and place

unbenannt

**Comment by ghost** [comment]
Thanks for the updates @matyro 

We can ignore the Travis error.  

Could you check the silk lines near the corners.  I think they may have moved from the horizontal when they were split up.  For example ...

image

**Comment by ghost** [comment]
Many thanks @matyro

**Pull request merged**
