### PR TITLE
Added Murata 3C

### PR DESCRIPTION
**Pull request by Matyro**
footprint

Added Murata 3C Footprint for an isolated DC-DC converter

Footprint and datasheet:
http://power.murata.com/data/power/ncl/kdc_cre1.pdf

Schematic symbol:
https://github.com/KiCad/kicad-library/pull/1439

### CODE REVIEW

**Comment by ghost** [comment]
Hi @matyro Thanks for the contribution.

Some initial comments ...

1. The diagram on p12 of the datasheet shows the hole size as 1.00 to 1.15mm diameter.  This is larger than the drill size you have on the pads.

2. Please make pin 1 a square pad instead of round.

**EDIT**

I have looked again at the diagram in the datasheet and also the photo of the device.

image
image

I think the plan view in that diagram is viewing the device **from below**. So the position of the footprint needs to be moved to keep pin 1 at left.  This is a rough sketch (Fab layer only).

image

3. The positions of the body outline lines on the Fab layer are slightly different from the dimensions shown in the datasheet.  The biggest difference is with the line at the top of the outline (as submitted).  In the footprint, it is at -1.1176mm.  The datasheet (p10) has 1.13mm.  

4. The right hand courtyard line is not vertical.

5. Even though you are not submitting a 3D model, please add a 3D model reference to the footprint.  Details in KLC 10.4 (https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention)

**Comment by ghost** [comment]
Posting updated image for reference.

image

**Comment by ghost** [comment]
Thanks for the updates.

With the larger drill sizes, the pad diameters should also increase.  IPC Level B specifies pad diameter =  drill hole diameter + 0.1mm annular ring + 0.5mm fabrication allowance. So with 1mm diameter drill, that makes the pads 1.6mm diameter.  

image

As a larger component, the courtyard clearance can be increased to 0.5mm from the current 0.25mm.  

The length of the chamfer corner can also be increased to 1mm in X and Y directions.

On the Silk layer, change the pin 1 marker from a chamfer to an external "L" shaped mark as shown below.  That way, it is still visible when the board is populated.

image

The footprint name should be `DCDC-Conv_muRata_CRE1xxxxxx3C`.  That is six `x` characters. The file name also needs an extra `x`:  `DCDC-Conv_muRata_CRE1xxxxxx3C.kicad_mod`.  And the same change is needed in the 3D model name.

**Comment by Shackmeister** [comment]
I believe the silkscreen indicator should be visible after mounting the component

**Comment by Matyro** [comment]
I would like to keep the soldering pads a bit smaller to provide enough clearence for a >1mm cut in the pcb to meet the 2kV insulation voltage criteria.

The possible best form is 1.4mm width and 1.6mm in height. This would allow ~1.15mm clearence between copper

**Comment by ghost** [comment]
> I would like to keep the soldering pads a bit smaller to provide enough clearence for a >1mm cut in the pcb to meet the 2kV insulation voltage criteria.

OK, that makes sense.  Would oval pads work?

image

**Comment by Matyro** [comment]
footprint

Pads are now 1.4 x 1.8mm 

1.4 for clearance
1.8 for additional stability

**Comment by ghost** [comment]
Thanks for making all those changes :smile:

A zero-length silkscreen line has crept in, triggering the Travis CI error.  I think if you delete line 28 from the file, that will fix it.

**Comment by ghost** [comment]
Thank you for the contribution :smile:

**Pull request merged**
